services:

  postgres:
    image: postgres:16
    container_name: minecraft-postgres
    restart: always

    environment:
      POSTGRES_DB: minecraft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: minecraft-grafana
    restart: always

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  grafana_data: