apiVersion: 1

datasources:
  - name: StonksTime
    uid: stonkstime
    type: postgres
    access: proxy
    isDefault: true
    editable: false
    url: postgres:5432
    user: stonkstime
    secureJsonData:
      password: stonkstime
    jsonData:
      database: stonkstime
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
